In [ ]:
#read the xl sheet

import pandas as pd
df=pd.read_excel('/content/Alarm Survey Data.xlsx')
print(df)

      survey_id  age  number_of_children  activity_level  sleep_quality  \
0             1   34                 3.0          active            3.0
1             2   31                 3.0           light            3.0
2             3   18                 0.0  light_activity            4.0
3             4   42                 4.0          active            4.0
4             5   30                 1.0  light_activity            1.0
...         ...  ...                 ...             ...            ...
6428       6362   27                 2.0          active            5.0
6429       6363   31                 1.0           light            4.0
6430       6364   26                 0.0  lightly active            5.0
6431       6365   27                 1.0          active            5.0
6432       6366   18                 0.0  lightly active            4.0

      number_of_snoozes alarm_rating
0                     1      5 stars
1                     3      3 stars
2                     1      1 stars
3                     1      4 stars
4                     4      3 stars
...                 ...          ...
6428                  0      5 stars
6429                  0      4 stars
6430                  0      3 stars
6431                  0      3 stars
6432                  0      1 stars

[6433 rows x 7 columns]

In [ ]:
#check the datatype  of each column
print(df.dtypes)
df.info()

survey_id               int64
age                     int64
number_of_children    float64
activity_level         object
sleep_quality         float64
number_of_snoozes       int64
alarm_rating           object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   float64
 3   activity_level      6433 non-null   object
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 351.9+ KB

In [ ]:
df.select_dtypes(include='object').columns

Index(['activity_level', 'alarm_rating'], dtype='object')

In [ ]:
df['alarm_rating']=pd.to_numeric(
    df['alarm_rating'].str.replace(' stars','')
)
print(df)

      survey_id  age  number_of_children  activity_level  sleep_quality  \
0             1   34                 3.0          active            3.0
1             2   31                 3.0           light            3.0
2             3   18                 0.0  light_activity            4.0
3             4   42                 4.0          active            4.0
4             5   30                 1.0  light_activity            1.0
...         ...  ...                 ...             ...            ...
6428       6362   27                 2.0          active            5.0
6429       6363   31                 1.0           light            4.0
6430       6364   26                 0.0  lightly active            5.0
6431       6365   27                 1.0          active            5.0
6432       6366   18                 0.0  lightly active            4.0

      number_of_snoozes  alarm_rating
0                     1             5
1                     3             3
2                     1             1
3                     1             4
4                     4             3
...                 ...           ...
6428                  0             5
6429                  0             4
6430                  0             3
6431                  0             3
6432                  0             1

[6433 rows x 7 columns]

In [ ]:
#Missing data check
df.isna().sum()

survey_id               0
age                     0
number_of_children      0
activity_level          0
sleep_quality         351
number_of_snoozes       0
alarm_rating            0
dtype: int64

In [ ]:
df[df.isna().any(axis=1)]

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
10,11,28,2.0,light_activity,NaN,3,4
18,19,38,2.0,lightly active,NaN,1,5
23,24,24,2.0,very active,NaN,1,5
26,27,25,2.0,lightly active,NaN,1,2
28,29,29,2.0,lightly active,NaN,1,2
...,...,...,...,...,...,...,...
6310,6311,30,2.0,very active,NaN,0,3
6319,6320,44,2.0,lightly active,NaN,0,3
6375,6309,32,3.0,light,NaN,0,3
6377,6311,30,2.0,very active,NaN,0,3
6386,6320,44,2.0,lightly active,NaN,0,3

In [ ]:
df['sleep_quality']=df['sleep_quality'].fillna(df['sleep_quality'].median())
print(df)

      survey_id  age  number_of_children  activity_level  sleep_quality  \
0             1   34                 3.0          active            3.0
1             2   31                 3.0           light            3.0
2             3   18                 0.0  light_activity            4.0
3             4   42                 4.0          active            4.0
4             5   30                 1.0  light_activity            1.0
...         ...  ...                 ...             ...            ...
6428       6362   27                 2.0          active            5.0
6429       6363   31                 1.0           light            4.0
6430       6364   26                 0.0  lightly active            5.0
6431       6365   27                 1.0          active            5.0
6432       6366   18                 0.0  lightly active            4.0

      number_of_snoozes  alarm_rating
0                     1             5
1                     3             3
2                     1             1
3                     1             4
4                     4             3
...                 ...           ...
6428                  0             5
6429                  0             4
6430                  0             3
6431                  0             3
6432                  0             1

[6433 rows x 7 columns]

In [ ]:
df['sleep_quality'].value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2612
3.0     997
1.0     103
Name: count, dtype: int64

In [ ]:
#Inconsistent text & typos Check
#Find inconsistent values
df['activity_level'].value_counts(dropna=False)

activity_level
active            2450
lightly active    2289
light_activity     691
very active        669
light              334
Name: count, dtype: int64

In [ ]:
#fix inconsistent values
df['activity_level']=df['activity_level'].replace(
    {
        'light':'lightly active',
        'light_activity':'lightly active'

    }
)
df['activity_level'].value_counts()

activity_level
lightly active    3314
active            2450
very active        669
Name: count, dtype: int64

In [ ]:
#Duplicate Data check
#Find duplicates
df[df.duplicated()]

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
6366,6300,31,2.0,active,5.0,0,3
6367,6301,27,2.0,lightly active,4.0,0,2
6368,6302,41,3.0,lightly active,5.0,0,2
6369,6303,25,0.0,lightly active,5.0,0,5
6370,6304,25,1.0,lightly active,5.0,0,2
...,...,...,...,...,...,...,...
6428,6362,27,2.0,active,5.0,0,5
6429,6363,31,1.0,lightly active,4.0,0,4
6430,6364,26,0.0,lightly active,5.0,0,3
6431,6365,27,1.0,active,5.0,0,3
6432,6366,18,0.0,lightly active,4.0,0,1

In [ ]:
#remove duplicates
df=df.drop_duplicates()
#verify
df.duplicated().sum()

np.int64(0)

In [ ]:
#5.outliers check
#i)Find outliers
#ii)Deal with outliers

In [ ]:
#quickly Explore updated DataFrame